services:
  web:
    image: sample:latest
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      
  storybook:
    image: storybook:latest
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6006:6006"
    volumes:
      - .:/app
    command: sh -c "npm install -D @storybook/react @storybook/builder-vite && npx storybook init --yes && npm run storybook -- --host 0.0.0.0 --ci"